Repository githubschool/launch, pull requests merged in 2021-02, with the labels that each got.

#14 Ticket-123: Edited caption to be more specific
  _slides/02-ericalloyd.md
Labels: bug-fix-123, hot-fix

#10 Modified caption to friendly message
  _slides/04-MarlaChat.md
Labels: bug-fix-010

#13 Edited Caption to be more specific
  _slides/03-0921johnb1965.md
Labels: bug-fix-001

#9 Vkanithi
  _slides/10-vkanithi.md
Labels: bug-fix-123

#16 This change is for Training purpose
  _slides/08-sarathkapa2.md
Labels: enhancement

#11 Edited My Caption
  _slides/06-SunilKMohanty.md
Labels: Bug fix - 1234567890
